### ISSUE TITLE
Hi, I think you're doing well
I have a lot of problem When I try to install metasploit.
This is the last error


### ISSUE THREAD

**Issue by Holy6Papa** [efxtv/efxtv#1]
[+] Press ENTER button to fix:                  [+] Okay got it...                              [+] Fixing metasploit...                        [+] Fixing....                                  [+] Almost fixed....                            sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb: No such file or directory              sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb: No such file or directory              sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb: No such file or directory  sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb: No such file or directory
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb: No such file or directory
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb: No such file or directory
[+] Cheers! Metasploit6 has been installed...
~ $ msfconsole
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Could not find nokogiri-1.8.0 in any of the sources
Run `bundle install` to install missing gems.
~ $ bundle install
Could not locate Gemfile
~ $

I don't know what I can do 
Please help me 
I need to use metasploit on my phone, 
I'm lost

**Comment by efxtv** [comment]
Latest Metasploit video on youtube is still working for others. Please check and install metasploit using emsf tool.

**Comment by efxtv** [comment]
https://youtu.be/iJiXnwR3lfI
